<a href="https://colab.research.google.com/github/rofiat13/projects/blob/main/Airline_Passenger_Satisfaction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


In [4]:
pass_sat= pd.read_csv("https://s3.us-west-1.wasabisys.com/dphi/datasets/230/train_dataset.csv?AWSAccessKeyId=ABSZWDH67WW3G8YX40WD&Signature=a12vpKYzlE03qAqkddjNGY0KLM8%3D&Expires=1654350818")

In [5]:
pass_sat.head()

Age  Flight Distance  Inflight wifi service  \
0   35              971                      3   
1   32             1092                      0   
2   46             2915                      0   
3   56             2556                      4   
4   54              468                      1   

   Departure/Arrival time convenient  Ease of Online booking  Gate location  \
0                                  4                       5              4   
1                                  0                       0              3   
2                                  5                       0              5   
3                                  4                       4              4   
4                                  4                       1              4   

   Food and drink  Online boarding  Seat comfort  Inflight entertainment  ...  \
0               2                3             3                       2  ...   
1               1                0             1                       1  ...   
2               3                4             5                       1  ...   
3               4                4             4                       3  ...   
4               4                1             4                       4  ...   

   Departure Delay in Minutes  Arrival Delay in Minutes  Gender_Female  \
0                         373                     358.0              0   
1                           0                       0.0              0   
2                           0                       0.0              1   
3                          19                      18.0              0   
4                           0                       0.0              0   

   Gender_Male  Type of Travel_Business travel  \
0            1                               1   
1            1                               1   
2            0                               1   
3            1                               1   
4            1                               0   

   Type of Travel_Personal Travel  Class_Business  Class_Eco  Class_Eco Plus  \
0                               0               0          1               0   
1                               0               0          1               0   
2                               0               1          0               0   
3                               0               1          0               0   
4                               1               0          1               0   

              satisfaction  
0  neutral or dissatisfied  
1                satisfied  
2                satisfied  
3                satisfied  
4  neutral or dissatisfied  

[5 rows x 26 columns]

In [6]:
pass_sat.shape

(50761, 26)

In [7]:
pass_sat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50761 entries, 0 to 50760
Data columns (total 26 columns):
 #   Column                             Non-Null Count  Dtype  
---  ------                             --------------  -----  
 0   Age                                50761 non-null  int64  
 1   Flight Distance                    50761 non-null  int64  
 2   Inflight wifi service              50761 non-null  int64  
 3   Departure/Arrival time convenient  50761 non-null  int64  
 4   Ease of Online booking             50761 non-null  int64  
 5   Gate location                      50761 non-null  int64  
 6   Food and drink                     50761 non-null  int64  
 7   Online boarding                    50761 non-null  int64  
 8   Seat comfort                       50761 non-null  int64  
 9   Inflight entertainment             50761 non-null  int64  
 10  On-board service                   50761 non-null  int64  
 11  Leg room service                   50761 non-null  int

In [8]:
pass_sat.describe()

Age  Flight Distance  Inflight wifi service  \
count  50761.000000     50761.000000           50761.000000   
mean      39.428518      1192.632730               2.737456   
std       15.127063       999.983962               1.329768   
min        7.000000        31.000000               0.000000   
25%       27.000000       413.000000               2.000000   
50%       40.000000       846.000000               3.000000   
75%       51.000000      1744.000000               4.000000   
max       85.000000      4983.000000               5.000000   

       Departure/Arrival time convenient  Ease of Online booking  \
count                       50761.000000            50761.000000   
mean                            3.058490                2.762455   
std                             1.525301                1.400141   
min                             0.000000                0.000000   
25%                             2.000000                2.000000   
50%                             3.000000                3.000000   
75%                             4.000000                4.000000   
max                             5.000000                5.000000   

       Gate location  Food and drink  Online boarding  Seat comfort  \
count   50761.000000    50761.000000     50761.000000  50761.000000   
mean        2.988081        3.203227         3.250015      3.439629   
std         1.278187        1.326620         1.348700      1.316720   
min         1.000000        0.000000         0.000000      1.000000   
25%         2.000000        2.000000         2.000000      2.000000   
50%         3.000000        3.000000         3.000000      4.000000   
75%         4.000000        4.000000         4.000000      5.000000   
max         5.000000        5.000000         5.000000      5.000000   

       Inflight entertainment  ...   Cleanliness  Departure Delay in Minutes  \
count            50761.000000  ...  50761.000000                50761.000000   
mean                 3.360158  ...      3.282126                   14.543094   
std                  1.331526  ...      1.311349                   36.729414   
min                  0.000000  ...      0.000000                    0.000000   
25%                  2.000000  ...      2.000000                    0.000000   
50%                  4.000000  ...      3.000000                    0.000000   
75%                  4.000000  ...      4.000000                   12.000000   
max                  5.000000  ...      5.000000                  933.000000   

       Arrival Delay in Minutes  Gender_Female   Gender_Male  \
count              50761.000000   50761.000000  50761.000000   
mean                  14.974469       0.506314      0.493686   
std                   37.390964       0.499965      0.499965   
min                    0.000000       0.000000      0.000000   
25%                    0.000000       0.000000      0.000000   
50%                    0.000000       1.000000      0.000000   
75%                   13.000000       1.000000      1.000000   
max                  952.000000       1.000000      1.000000   

       Type of Travel_Business travel  Type of Travel_Personal Travel  \
count                    50761.000000                    50761.000000   
mean                         0.693938                        0.306062   
std                          0.460860                        0.460860   
min                          0.000000                        0.000000   
25%                          0.000000                        0.000000   
50%                          1.000000                        0.000000   
75%                          1.000000                        1.000000   
max                          1.000000                        1.000000   

       Class_Business     Class_Eco  Class_Eco Plus  
count    50761.000000  50761.000000    50761.000000  
mean         0.480605      0.447509        0.071886  
std          0.499629      0.497242        0.258301  
min          0.000000  

In [9]:
pass_sat['satisfaction'].value_counts()

neutral or dissatisfied    28764
satisfied                  21997
Name: satisfaction, dtype: int64

In [10]:
from seaborn.utils import iqr
Q1= pass_sat.quantile(0.25)
Q3= pass_sat.quantile(0.75)
IQR= Q3-Q1
print(IQR)


Age                                    24.0
Flight Distance                      1331.0
Inflight wifi service                   2.0
Departure/Arrival time convenient       2.0
Ease of Online booking                  2.0
Gate location                           2.0
Food and drink                          2.0
Online boarding                         2.0
Seat comfort                            3.0
Inflight entertainment                  2.0
On-board service                        2.0
Leg room service                        2.0
Baggage handling                        2.0
Checkin service                         1.0
Inflight service                        2.0
Cleanliness                             2.0
Departure Delay in Minutes             12.0
Arrival Delay in Minutes               13.0
Gender_Female                           1.0
Gender_Male                             1.0
Type of Travel_Business travel          1.0
Type of Travel_Personal Travel          1.0
Class_Business                  

In [11]:
print(pass_sat<(Q1-1.5*IQR)) or (pass_sat>Q3+1.5*IQR)

         Age  Arrival Delay in Minutes  Baggage handling  Checkin service  \
0      False                     False             False            False   
1      False                     False             False             True   
2      False                     False             False            False   
3      False                     False             False            False   
4      False                     False             False            False   
...      ...                       ...               ...              ...   
50756  False                     False             False            False   
50757  False                     False             False            False   
50758  False                     False             False            False   
50759  False                     False             False            False   
50760  False                     False             False            False   

       Class_Business  Class_Eco  Class_Eco Plus  Cleanliness  \
0         

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version.  Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  """Entry point for launching an IPython kernel.


Age  Arrival Delay in Minutes  Baggage handling  Checkin service  \
0      False                      True             False            False   
1      False                     False             False            False   
2      False                     False             False            False   
3      False                     False             False            False   
4      False                     False             False            False   
...      ...                       ...               ...              ...   
50756  False                      True             False            False   
50757  False                     False             False            False   
50758  False                     False             False            False   
50759  False                     False             False            False   
50760  False                      True             False            False   

       Class_Business  Class_Eco  Class_Eco Plus  Cleanliness  \
0               False      False           False        False   
1               False      False           False        False   
2               False      False           False        False   
3               False      False           False        False   
4               False      False           False        False   
...               ...        ...             ...          ...   
50756           False      False           False        False   
50757           False      False           False        False   
50758           False      False           False        False   
50759           False      False           False        False   
50760           False      False           False        False   

       Departure Delay in Minutes  Departure/Arrival time convenient  ...  \
0                            True                              False  ...   
1                           False                              False  ...   
2                           False                              False  ...   
3                           False                              False  ...   
4                           False                              False  ...   
...                           ...                                ...  ...   
50756                        True                              False  ...   
50757                       False                              False  ...   
50758                       False                              False  ...   
50759                       False                              False  ...   
50760                        True                              False  ...   

       Inflight entertainment  Inflight service  Inflight wifi service  \
0                       False             False                  False   
1                       False             False                  False   
2                       False             False                  False   
3                       False             False                  False   
4                       False             False                  False   
...                       ...               ...                    ...   
50756                   False             False                  False   
50757                   False             False                  False   
50758                   False             False                  False   
50759                   False             False                  False   
50760                   False             False                  False   

       Leg room service  On-board service  Online boarding  Seat comfort  \
0                 False             False            False         False   
1                 False             False            False         False   
2                 False             False            False         False   
3                 False             False            False         False   
4                 False             False            False         False   
...                 ...          

In [12]:
print(pass_sat['Flight Distance'].quantile(0.5))
print(pass_sat['Flight Distance'].quantile(0.95))
print(pass_sat['Flight Distance'].quantile(0.75))

846.0
3392.0
1744.0


In [13]:
pass_sat['Flight Distance']=np.where(pass_sat['Flight Distance']>3392.0,1744.0,pass_sat['Flight Distance'])
pass_sat['Flight Distance'].describe()

count    50761.000000
mean      1094.429247
std        828.522274
min         31.000000
25%        413.000000
50%        846.000000
75%       1744.000000
max       3392.000000
Name: Flight Distance, dtype: float64

In [14]:
print(pass_sat['Departure Delay in Minutes'].quantile(0.5))
print(pass_sat['Departure Delay in Minutes'].quantile(0.95))
print(pass_sat['Departure Delay in Minutes'].quantile(0.75))

0.0
76.0
12.0


In [15]:
pass_sat['Departure Delay in Minutes']=np.where(pass_sat['Departure Delay in Minutes']>76.0,12.0,pass_sat['Departure Delay in Minutes'])
pass_sat['Departure Delay in Minutes'].describe()

count    50761.000000
mean         8.090857
std         14.783153
min          0.000000
25%          0.000000
50%          0.000000
75%         12.000000
max         76.000000
Name: Departure Delay in Minutes, dtype: float64

In [16]:
print(pass_sat['Arrival Delay in Minutes'].quantile(0.5))
print(pass_sat['Arrival Delay in Minutes'].quantile(0.95))
print(pass_sat['Arrival Delay in Minutes'].quantile(0.75))

0.0
79.0
13.0


In [17]:
pass_sat['Arrival Delay in Minutes']=np.where(pass_sat['Arrival Delay in Minutes']>79.0,13.0,pass_sat['Arrival Delay in Minutes'])
pass_sat['Arrival Delay in Minutes'].describe()

count    50761.000000
mean         8.457556
std         15.147679
min          0.000000
25%          0.000000
50%          0.000000
75%         13.000000
max         79.000000
Name: Arrival Delay in Minutes, dtype: float64

In [18]:
y=pass_sat['satisfaction']
x=pass_sat.drop(['satisfaction'],axis=1)

In [19]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [20]:
x.head()

Age  Flight Distance  Inflight wifi service  \
0   35            971.0                      3   
1   32           1092.0                      0   
2   46           2915.0                      0   
3   56           2556.0                      4   
4   54            468.0                      1   

   Departure/Arrival time convenient  Ease of Online booking  Gate location  \
0                                  4                       5              4   
1                                  0                       0              3   
2                                  5                       0              5   
3                                  4                       4              4   
4                                  4                       1              4   

   Food and drink  Online boarding  Seat comfort  Inflight entertainment  ...  \
0               2                3             3                       2  ...   
1               1                0             1                       1  ...   
2               3                4             5                       1  ...   
3               4                4             4                       3  ...   
4               4                1             4                       4  ...   

   Cleanliness  Departure Delay in Minutes  Arrival Delay in Minutes  \
0            3                        12.0                      13.0   
1            1                         0.0                       0.0   
2            3                         0.0                       0.0   
3            4                        19.0                      18.0   
4            4                         0.0                       0.0   

   Gender_Female  Gender_Male  Type of Travel_Business travel  \
0              0            1                               1   
1              0            1                               1   
2              1            0                               1   
3              0            1                               1   
4              0            1                               0   

   Type of Travel_Personal Travel  Class_Business  Class_Eco  Class_Eco Plus  
0                               0               0          1               0  
1                               0               0          1               0  
2                               0               1          0               0  
3                               0               1          0               0  
4                               1               0          1               0  

[5 rows x 25 columns]

In [21]:
print(y)

[0 1 1 ... 1 0 0]


In [22]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train, y_test = train_test_split(x,y,test_size=0.3, random_state=0)

In [23]:
print(y_train.shape)
print(y_test.shape)
print(x_test.shape)
print(x_train.shape)

(35532,)
(15229,)
(15229, 25)
(35532, 25)


In [24]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
x_train= sc.fit_transform(x_train)
x_test= sc.transform(x_test)

In [25]:
from sklearn.decomposition import PCA
pca= PCA()
pca.fit(x_train)

PCA()

In [26]:
pca.n_components_

25

In [27]:
pca.transform(x_train)
pca.transform(x_test)

array([[-1.14019769e+00,  2.14650233e+00,  1.95413451e+00, ...,
        -3.69369099e-16,  2.69031743e-16,  5.93263551e-18],
       [-3.60020632e-01,  1.23752137e+00, -4.02964785e+00, ...,
        -7.02436006e-16,  4.69871378e-17, -4.95785157e-17],
       [ 1.40298960e+00, -2.79131802e+00,  8.27033196e-01, ...,
        -1.89549565e-17,  3.24542894e-16,  6.02511644e-17],
       ...,
       [-2.47618791e-01,  2.52541895e+00, -2.03097996e-01, ...,
        -3.69369099e-16, -2.86079770e-16, -4.95785157e-17],
       [-2.55254807e+00, -2.54416158e-01, -2.24292436e+00, ...,
         1.01147079e-15, -2.86079770e-16, -4.95785157e-17],
       [-2.97271716e-01,  1.56436652e+00,  4.16283202e-02, ...,
        -4.92661467e-16, -4.02455846e-16, -1.24900090e-16]])

In [28]:
from sklearn.linear_model import LogisticRegression
clf=LogisticRegression(random_state=1)
clf=clf.fit(x_train, y_train)

In [29]:
pred=clf.predict(x_test)

In [30]:
pred

array([1, 1, 0, ..., 1, 1, 0])

In [31]:
clf.score(x_test,y_test)

0.8625648433908989

In [32]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,pred)

0.8625648433908989

In [33]:
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(y_test, pred)
cm

array([[7657,  946],
       [1147, 5479]])

In [34]:
from sklearn.tree import DecisionTreeClassifier
clf1=DecisionTreeClassifier()
clf1= clf1.fit(x_train,y_train)

In [35]:
prediction=clf1.predict(x_test)

In [36]:
clf1.score(x_test,y_test)

0.9289513428327533

In [37]:
from sklearn.metrics import confusion_matrix
cm1= confusion_matrix(y_test, prediction)
cm1

array([[8061,  542],
       [ 540, 6086]])

In [38]:
from sklearn import tree

In [40]:
from sklearn.metrics import classification_report
print(classification_report(y_test, prediction))

              precision    recall  f1-score   support

           0       0.94      0.94      0.94      8603
           1       0.92      0.92      0.92      6626

    accuracy                           0.93     15229
   macro avg       0.93      0.93      0.93     15229
weighted avg       0.93      0.93      0.93     15229

