<a href="https://colab.research.google.com/github/rofiat13/projects/blob/main/predicting_the_price_of_houses.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
 import pandas as pd
 import numpy as np
 import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv('House_Price.csv')

In [ ]:
df.head()

price  crime_rate  resid_area  ...  rainfall  bus_ter     parks
0   24.0     0.00632       32.31  ...        23      YES  0.049347
1   21.6     0.02731       37.07  ...        42      YES  0.046146
2   34.7     0.02729       37.07  ...        38      YES  0.045764
3   33.4     0.03237       32.18  ...        45      YES  0.047151
4   36.2     0.06905       32.18  ...        55      YES  0.039474

[5 rows x 19 columns]

In [ ]:
df.describe()

price  crime_rate  resid_area  ...  n_hot_rooms    rainfall       parks
count  506.000000  506.000000  506.000000  ...   506.000000  506.000000  506.000000
mean    22.528854    3.613524   41.136779  ...    13.041605   39.181818    0.054454
std      9.182176    8.601545    6.860353  ...     5.238957   12.513697    0.010632
min      5.000000    0.006320   30.460000  ...    10.057600    3.000000    0.033292
25%     17.025000    0.082045   35.190000  ...    11.189800   28.000000    0.046464
50%     21.200000    0.256510   39.690000  ...    12.720000   39.000000    0.053507
75%     25.000000    3.677082   48.100000  ...    14.170800   50.000000    0.061397
max     50.000000   88.976200   57.740000  ...   101.120000   60.000000    0.086711

[8 rows x 16 columns]

In [ ]:
df.shape

(506, 19)

In [ ]:
x=df.iloc[:,1:]
y=df['price']

In [ ]:
x.head()

crime_rate  resid_area  air_qual  ...  rainfall  bus_ter     parks
0     0.00632       32.31     0.538  ...        23      YES  0.049347
1     0.02731       37.07     0.469  ...        42      YES  0.046146
2     0.02729       37.07     0.469  ...        38      YES  0.045764
3     0.03237       32.18     0.458  ...        45      YES  0.047151
4     0.06905       32.18     0.458  ...        55      YES  0.039474

[5 rows x 18 columns]

In [ ]:
print(x.shape)
print(y.shape)

(506, 18)
(506,)


In [ ]:
df.isnull().sum()

price          0
crime_rate     0
resid_area     0
air_qual       0
room_num       0
age            0
dist1          0
dist2          0
dist3          0
dist4          0
teachers       0
poor_prop      0
airport        0
n_hos_beds     8
n_hot_rooms    0
waterbody      0
rainfall       0
bus_ter        0
parks          0
dtype: int64

In [ ]:
from sklearn.impute import SimpleImputer
imputer= SimpleImputer(missing_values=np.nan, strategy='mean',)
imputer= imputer.fit(x.iloc[:,12:13])
x.iloc[:,12:13]=imputer.transform(x.iloc[:,12:13])

In [ ]:
x.isnull().sum()

crime_rate     0
resid_area     0
air_qual       0
room_num       0
age            0
dist1          0
dist2          0
dist3          0
dist4          0
teachers       0
poor_prop      0
airport        0
n_hos_beds     0
n_hot_rooms    0
waterbody      0
rainfall       0
bus_ter        0
parks          0
dtype: int64

In [ ]:
cat_df=df.select_dtypes(include=['object']).copy()

In [ ]:
cat_df.head()

airport waterbody bus_ter
0     YES     River     YES
1      NO      Lake     YES
2      NO      None     YES
3     YES      Lake     YES
4      NO      Lake     YES

In [ ]:
features=cat_df.columns
features

Index(['airport', 'waterbody', 'bus_ter'], dtype='object')

In [ ]:
x.head()

crime_rate  resid_area  air_qual  ...  rainfall  bus_ter     parks
0     0.00632       32.31     0.538  ...        23      YES  0.049347
1     0.02731       37.07     0.469  ...        42      YES  0.046146
2     0.02729       37.07     0.469  ...        38      YES  0.045764
3     0.03237       32.18     0.458  ...        45      YES  0.047151
4     0.06905       32.18     0.458  ...        55      YES  0.039474

[5 rows x 18 columns]

In [ ]:
for feature in features:
  x[feature]=x[feature].astype('category')
  x[feature]=x[feature].cat.codes

In [ ]:
x.head()

crime_rate  resid_area  air_qual  ...  rainfall  bus_ter     parks
0     0.00632       32.31     0.538  ...        23        0  0.049347
1     0.02731       37.07     0.469  ...        42        0  0.046146
2     0.02729       37.07     0.469  ...        38        0  0.045764
3     0.03237       32.18     0.458  ...        45        0  0.047151
4     0.06905       32.18     0.458  ...        55        0  0.039474

[5 rows x 18 columns]

In [ ]:
x['avg-dist']=(x['dist1']+x['dist2']+x['dist3']+x['dist4'])/4

In [ ]:
x.drop(columns=['dist1','dist2','dist3','dist4'], inplace=True)

In [ ]:
x.drop('bus_ter', axis=1, inplace=True)

In [ ]:
x.head()

crime_rate  resid_area  air_qual  ...  rainfall     parks  avg-dist
0     0.00632       32.31     0.538  ...        23  0.049347    4.0875
1     0.02731       37.07     0.469  ...        42  0.046146    4.9675
2     0.02729       37.07     0.469  ...        38  0.045764    4.9675
3     0.03237       32.18     0.458  ...        45  0.047151    6.0650
4     0.06905       32.18     0.458  ...        55  0.039474    6.0625

[5 rows x 14 columns]

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x,y, test_size=0.30)

In [ ]:
print(x_train.shape)
print(x_test.shape)

(354, 14)
(152, 14)


In [ ]:
print(y_train.shape)
print(y_test.shape)

(354,)
(152,)


In [ ]:
from sklearn.preprocessing import StandardScaler
ss= StandardScaler()
x_train= ss.fit_transform(x_train)
x_test=ss.transform(x_test)

In [ ]:
from sklearn.decomposition import PCA
pca= PCA(0.70)
pca.fit(x_train)

PCA(copy=True, iterated_power='auto', n_components=0.7, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [ ]:
pca.n_components_

6

In [ ]:
pca.transform(x_train)
pca.transform(x_test)

array([[ 7.62209925e-01,  5.69929443e-01, -7.52605390e-01,
        -1.32314035e-01,  1.76671041e-01,  2.00246653e-01],
       [-4.98160507e-01,  4.57125616e-02,  1.49634435e+00,
        -6.05871867e-01,  1.58902348e+00,  8.88888513e-02],
       [ 2.24834864e+00, -4.20382046e-01,  3.01308991e-01,
        -2.77409848e-01,  1.39356968e-01, -1.86305297e+00],
       [-1.20063564e+00, -2.28445954e-01, -9.72116358e-01,
         7.88465517e-01,  4.56795006e-01, -1.37310153e+00],
       [-1.12044106e+00,  8.51671537e-01,  1.07215261e+00,
         1.09976452e-01,  7.33404100e-01,  2.52983007e-01],
       [ 2.77613570e+00,  2.62061977e-01,  9.44951943e-01,
         7.18799312e-01, -9.06430004e-02, -1.44200489e+00],
       [ 3.15637660e+00, -8.13236429e-01,  6.54206326e-01,
        -1.27851363e-01,  2.06158685e-01, -2.23400880e+00],
       [ 8.44712862e-01, -1.43637704e-01,  6.36966957e-01,
        -1.13835387e+00, -6.87738961e-01,  1.01660139e+00],
       [-1.62457513e+00,  1.08023042e+00, -4.104

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor

In [ ]:
from sklearn.model_selection import GridSearchCV
reg= GridSearchCV(GradientBoostingRegressor(learning_rate=0.1), param_grid={'max_depth':[3],
                                                                           'loss':['ls'],
                                                                           'random_state':[0],
                                                                           },return_train_score= False)

In [ ]:
reg.fit(x_train, y_train)

GridSearchCV(cv=None, error_score=nan,
             estimator=GradientBoostingRegressor(alpha=0.9, ccp_alpha=0.0,
                                                 criterion='friedman_mse',
                                                 init=None, learning_rate=0.1,
                                                 loss='ls', max_depth=3,
                                                 max_features=None,
                                                 max_leaf_nodes=None,
                                                 min_impurity_decrease=0.0,
                                                 min_impurity_split=None,
                                                 min_samples_leaf=1,
                                                 min_samples_split=2,
                                                 min_weight_fraction_leaf=0.0,
                                                 n_estimators=100,
                                                 n_iter_no_change=None,
              

In [ ]:
pred= reg.predict(x_test)
pred

array([18.39609065, 21.85216334, 16.9909538 , 22.9629398 , 27.24727799,
       16.31932192, 31.18472423, 17.66053114, 35.69441091, 20.05193656,
       16.35098971, 21.52669331, 14.24898437, 24.70037472, 32.37841601,
       16.07664673, 43.3988663 , 19.39236425, 25.15522787, 25.71668856,
       10.68387281, 21.57457488, 12.60689264, 18.34379671, 15.52018482,
        8.22923213, 17.89985024, 17.98723535, 20.56858067, 22.79220917,
       12.5327773 , 26.84645556, 22.71311544, 20.29102736, 19.23603094,
       48.78190449, 22.71787389, 14.68220094, 16.70922802, 21.21476516,
       20.69517092, 20.95945856, 11.08368929, 20.72313726, 28.35906777,
       11.10559686, 22.86171488, 16.75458994, 18.35484878, 27.2128027 ,
       23.5812556 , 13.69165186, 13.37782978,  8.80062797, 13.19329807,
       44.72891282, 19.76087086, 19.52399573, 33.48689036, 21.67300132,
       19.36876921, 12.13168252, 33.48824293, 18.20878504, 47.79035884,
       20.61442393,  9.11212413, 20.3172868 ,  9.24921398, 22.57

In [ ]:
reg.score(x_test, y_test)

0.8030108719617923

In [ ]:
result_df= pd.DataFrame(reg.cv_results_)
result_df.head()

mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
0       0.120035      0.007015  ...        0.029942                1

[1 rows x 16 columns]

In [ ]:
print(reg.best_score_)
print(reg.best_params_)

0.8835053814346084
{'loss': 'ls', 'max_depth': 3, 'random_state': 0}


In [ ]:
from sklearn.metrics import mean_squared_error
error=mean_squared_error(y_test, pred)
np.sqrt(error)

4.000145572962761

In [ ]:
from sklearn.ensemble import RandomForestRegressor

In [ ]:
reg_1= GridSearchCV(RandomForestRegressor(),param_grid={
                                                        'criterion': ['mse'],
                                                        'random_state':[0]
                                                        }, return_train_score= False)
reg_1.fit(x_train, y_train)

GridSearchCV(cv=None, error_score=nan,
             estimator=RandomForestRegressor(bootstrap=True, ccp_alpha=0.0,
                                             criterion='mse', max_depth=None,
                                             max_features='auto',
                                             max_leaf_nodes=None,
                                             max_samples=None,
                                             min_impurity_decrease=0.0,
                                             min_impurity_split=None,
                                             min_samples_leaf=1,
                                             min_samples_split=2,
                                             min_weight_fraction_leaf=0.0,
                                             n_estimators=100, n_jobs=None,
                                             oob_score=False, random_state=None,
                                             verbose=0, warm_start=False),
             iid='deprecated', n

In [ ]:
pred_1= reg_1.predict(x_test)
pred_1

array([19.672, 23.881, 16.914, 22.257, 27.139, 15.91 , 27.246, 18.499,
       32.936, 20.684, 14.971, 20.882, 14.602, 29.104, 31.14 , 15.071,
       44.876, 19.587, 25.538, 25.561, 11.902, 21.451, 12.195, 16.667,
       17.53 ,  8.485, 15.946, 15.18 , 21.044, 21.62 , 14.585, 26.264,
       22.013, 20.311, 20.545, 47.561, 22.854, 16.139, 15.366, 20.917,
       21.169, 20.96 , 12.237, 20.98 , 27.895, 11.739, 22.543, 15.826,
       18.266, 27.885, 23.772, 14.201, 12.731, 11.086, 17.582, 36.931,
       19.317, 20.041, 33.701, 22.335, 20.666, 11.938, 29.294, 19.968,
       48.412, 21.651,  9.837, 20.858, 10.72 , 22.78 , 30.282, 25.539,
       26.341, 20.677, 34.035, 20.432, 14.197, 14.844, 11.155, 45.703,
       14.679, 24.913, 20.567, 21.174, 15.726, 31.568, 23.809, 14.855,
       20.443, 48.401, 34.49 , 11.8  , 40.529, 15.523, 35.597, 30.352,
       21.293, 22.622,  9.509,  8.751, 22.322, 29.566, 24.735, 20.323,
       33.144, 14.746, 23.503, 17.412, 16.744, 28.805, 13.008, 13.884,
      

In [ ]:
reg_1.score(x_test, y_test)

0.8044886977593242

In [ ]:
result_df_1= pd.DataFrame(reg.cv_results_)
result_df_1.head()

mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
0       0.120035      0.007015  ...        0.029942                1

[1 rows x 16 columns]

In [ ]:
result_df_1[['param_max_depth','param_random_state','mean_test_score']].head()

param_max_depth param_random_state  mean_test_score
0               3                  0         0.883505

In [ ]:
print(reg_1.best_score_)
print(reg_1.best_params_)

0.8657411397405047
{'criterion': 'mse', 'random_state': 0}


In [ ]:
error_1= mean_squared_error(y_test, pred_1)
np.sqrt(error_1)

3.985112643689605

In [ ]:
from sklearn.neighbors import KNeighborsRegressor

In [ ]:
from sklearn.model_selection import GridSearchCV
reg_2= GridSearchCV(KNeighborsRegressor(), param_grid={'n_neighbors': [5],
                                                       'weights':['uniform'],
                                                       'algorithm':['auto'],
                                                       'leaf_size':[30]
                                                       },return_train_score= False)
reg_2.fit(x_train, y_train)

GridSearchCV(cv=None, error_score=nan,
             estimator=KNeighborsRegressor(algorithm='auto', leaf_size=30,
                                           metric='minkowski',
                                           metric_params=None, n_jobs=None,
                                           n_neighbors=5, p=2,
                                           weights='uniform'),
             iid='deprecated', n_jobs=None,
             param_grid={'algorithm': ['auto'], 'leaf_size': [30],
                         'n_neighbors': [5], 'weights': ['uniform']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [ ]:
pred_2=reg_2.predict(x_test)
pred_2

array([21.08, 23.38, 13.56, 24.02, 27.64, 12.46,  8.3 , 18.46, 27.92,
       21.88, 15.66, 20.96, 15.66, 21.58, 34.8 , 16.12, 38.88, 20.78,
       27.06, 26.04, 11.34, 19.86, 15.96, 15.54, 20.1 , 11.56, 16.5 ,
       14.06, 20.42, 20.02, 13.32, 28.54, 24.3 , 18.52, 19.4 , 38.44,
       22.22, 17.26, 15.76, 18.4 , 20.42, 20.12, 12.38, 20.22, 24.66,
       10.28, 20.96, 15.52, 18.96, 22.8 , 22.48, 16.08, 15.9 , 12.46,
       17.52, 24.94, 22.46, 19.36, 31.34, 22.04, 19.54, 15.  , 26.84,
       21.08, 36.66, 23.84, 12.12, 21.52, 12.12, 27.46, 25.4 , 20.74,
       23.  , 24.06, 19.38, 20.96, 23.14, 16.44, 13.04, 34.  , 14.12,
       24.16, 24.02, 21.5 , 15.66, 27.62, 24.1 , 16.26, 22.28, 43.02,
       29.28, 14.44, 34.22, 17.58, 33.04, 14.36, 20.88, 23.54, 13.44,
        9.26, 24.68, 28.18, 24.28, 24.56, 26.3 , 15.3 , 19.18, 13.44,
       14.6 , 27.38, 10.22, 13.68, 15.3 , 20.  , 20.32, 22.18, 24.48,
       20.14, 15.12, 21.04, 29.56, 34.42, 24.8 , 38.2 , 22.08, 48.02,
       21.56, 27.06,

In [ ]:
reg_2.score(x_test, y_test)

0.725971003808607

In [ ]:
result_df_2= pd.DataFrame(reg.cv_results_)
result_df_2.head()

mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
0       0.120035      0.007015  ...        0.029942                1

[1 rows x 16 columns]

In [ ]:
print(reg_2.best_score_)
print(reg_2+.best_params_)

0.6740670283533785
{'algorithm': 'auto', 'leaf_size': 30, 'n_neighbors': 5, 'weights': 'uniform'}


In [ ]:
error_2= mean_squared_error(y_test, pred_2)
np.sqrt(error_2)

4.717945583229611

In [ ]:
from sklearn.svm import SVR


In [ ]:
reg_4= GridSearchCV(SVR(), param_grid={
       'C':[1.0],
       'kernel':['rbf'],
       'gamma':['scale'],
       'degree':[3]
       },
       cv=5, return_train_score= False
reg_4.fit(x_train, y_train)
     

In [ ]:
pred_3= reg_3.predict(x_test)

In [ ]:
reg_3.score(x_test, y_test)

In [ ]:
result_df_3= pd.DataFrame(reg_3.cv_results_)
result_df_3.head()

In [ ]:
result_df_3[['param_kernel', 'param_gamma', 'param_degree', 'mean_test_score']].head()

In [ ]:
print(reg_3.best_params_)
print(reg_3.best_score_)

In [ ]:
error_3= mean_squared_error(y_test, pred_3)
np.sqrt(error_3)